#!/usr/bin/env fish
#lee2sman

#dependencies: ffmpeg with ffprobe

#defaults
set input inputfile
set output output.mp4

#--------REQUIREMENTS------------
function check_prereq
  if not command -sq ffmpeg
	echo "vidchop requires ffmpeg but it's not installed. Exiting."
	exit 1
    end
end

#----------FUNCTIONS-------------

function info
  ls -hs $input 
  length
end

function length
  #mp4
  ffprobe -v error -sexagesimal -select_streams v:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 $input
end

function seconds
  #mp4
  ffprobe -v error -select_streams v:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 $input
end

function reduce
  #mp4
  ffmpeg -i $input -vcodec libx265 -crf 28 $output
end

function trim
  ffmpeg -ss $start -to $stop -i $input -c copy $output
end

function combine
  ffmpeg -safe 0 -f concat -i $list -c copy $output
end

function usage
  echo "usage: vidchop <option> <input-file> [<output-file>]"
  
  echo ""
  echo "   --help    | -h  : prints this help"
  echo "   --output  | -o  : output file. (default output.mp4)"
  echo "INFO:"
  echo "   --info    | -i"
  echo "   --length  | -l  : get length in HH:mm:ss.ms"
  echo "   --seconds | -s  : get length in seconds"
  echo "PROCESS:"
  echo "    --reduce | -r  : fast compress input file"
  echo "    --trim   | -t  : cut from hh:mm:ss to hh:mm:ss"
  echo "    --combine| -c  : sequentially combine videos input list file"
  echo ""
  echo "For combining videos, listfile must be formatted:"
  echo "file 'file1.mp4'"
  echo "file 'file2.mp4'"
  echo "..etc.."
end

function check_args
  argparse h/help o/output= i/info= l/length= s/seconds= r/reduce= t/trim= c/combine -- $argv
  or exit 1

  if set -q _flag_h
      usage
      exit
  end

  if set _q _flag_o
    set output $_flag_o
    echo $output
  end

  if set -q _flag_i
    set input $_flag_i
    info
  end

  if set -q _flag_l
    set input $_flag_l
    length
  end

  if set -q _flag_s
    set input $_flag_s
    seconds
  end

  if set -q _flag_r
    set input $_flag_r
    reduce
  end

  if set -q _flag_t
    set input $_flag_t
    trim
  end

  if set -q _flag_c
    set list $_flag_c
    combine
  end
end

#---------------MAIN---------------
check_prereq
check_args $argv
